### ISSUE TITLE
syntax-update-54.ru : missing a absolute IRI ?

### ISSUE THREAD

**Issue by BorderCloud** [BorderCloud/TFT-tests#3]
in 'syntax-update-53.ru' test the IRI's of the graphs are not absolute( for g1 and g2). The absolute IRI's must have a mandatory 'schema' part ...

``` SPARQL
PREFIX : <http://www.example.org/>

INSERT DATA {
              GRAPH<g1> { _:b1 :p :o }
              GRAPH<g2> { _:b1 :p :o }
            }
```

[see the test](https://github.com/BorderCloud/TFT-tests/blob/master/sparql11-test-suite/syntax-update-1/syntax-update-54.ru)

**Comment by VladimirAlexiev** [comment]
This bug is about https://github.com/BorderCloud/TFT-tests/blob/master/sparql11-test-suite/syntax-update-1/syntax-update-53.ru (sorry, wrong filename). Please reopen it.

**Comment by VladimirAlexiev** [comment]
Sorry, I see in #4 that you prepend a base before running the queries. Keep it closed. Eg:
```sparql
BASE <https://github.com/BorderCloud/TFT-tests/blob/master/sparql11-test-suite/property-path/>
```
