### ISSUE TITLE
property-path/path-ng-01.rq needs a BASE

### ISSUE THREAD

**Issue by VladimirAlexiev** [BorderCloud/TFT-tests#4]
https://github.com/BorderCloud/TFT-tests/blob/master/sparql11-test-suite/property-path/path-ng-01.rq:
```
prefix :  <http://www.example.org/>
select ?t
where {
  GRAPH <ng-01.ttl> {
    ?s :p1* ?t }
}
```
Sesame reports "Not a valid (absolute) URI: ng-01.ttl". The query needs a BASE.

Maybe many of the w3c tests involving graphs, suffer from a similar problem.

**Comment by BorderCloud** [comment]
Sorry for my silence, I was very busy.

I understood your problem. 
Now, TFT inserts in each query the base URI.
You can see the result in the new score: http://sparqlscore.com/

Bye

**Comment by VladimirAlexiev** [comment]
Thanks!!!
Though I still don't understand which is "THE base uri" :-)

**Comment by BorderCloud** [comment]
Base uri is the same concept to resolve the relative URL in a page html.

```
You can write in your page HTML <a href="Thing.html">Thing</a>
 only because your navigator knows the base URL of the current page.
For example, in the page http://example.org/index.html , 
you have the relative link <a href="Thing.html">Thing</a> so the navigator
 can resolve this relative URL in absolute URL with the Base URL "http://example.org/" 
of the current page in the navigator. So the absolute link is <http://example.org/Thing.htm>
```

TFT is like the navigator and write now the base URI with the relative URI in your query.

For example :
```
BASE <https://github.com/BorderCloud/TFT-tests/blob/master/sparql11-test-suite/property-path/>
prefix :  <http://www.example.org/>
select ?t
where {
  GRAPH <ng-01.ttl> {
    ?s :p1* ?t }
}
```
The precedent query is equivalent to :
```
prefix :  <http://www.example.org/>
select ?t
where {
  GRAPH <https://github.com/BorderCloud/TFT-tests/blob/master/sparql11-test-suite/property-path/ng-01.ttl> {
    ?s :p1* ?t }
}
```

(Sorry for my english)

**Comment by VladimirAlexiev** [comment]
Ok, I see!
Though maybe this is a better base https://raw.githubusercontent.com/BorderCloud/TFT-tests/master/sparql11-test-suite/property-path/ since it serves the actual file.
(The one you used serves a webpage where the file is displayed)

Of course, this is optional since these URLs aren't really used by anything. At least currently.
