### ISSUE TITLE
Fuzzy requirement : AVG

### ISSUE THREAD

**Issue by BorderCloud** [BorderCloud/TFT-tests#9]
As Sebastian Schaffert said:

> **AVG should accept all numeric return types**
> The tests currently require that the result of AVG always is the same type as the input arguments. However, the SPARQL 1.1 specification defines AVG as to return any numeric value. The tests should therefore only check if the return type is numeric.
> This also makes sense when you take e.g. the example of the average of the integers 1 and 2 - which is the double or decimal value 1.5.

For me the requirements are fuzzy because it's not possible to make unit tests for all the cases. The AVG's test are logic but it is necessary to add more unit tests for the functions like AVG and so clarify the requirements.

What did you think ?

**Comment by VladimirAlexiev** [comment]
As far as I can see, https://www.w3.org/TR/sparql11-query/#defn_aggAvg doesn't specify the output datatype.
So the best would be if you can compare the expected and result numerically, but I guess the result comparator doesn't have that flexibility.

**Comment by BorderCloud** [comment]
A unit test don't need to flexible...  It's the specification need to be clear.

**Comment by VladimirAlexiev** [comment]
You can't change the spec. `"1.5"^^xsd:decimal` and `"1.5"^^xsd:float` are equivalent (compatible) results of  `avg()` so your comparator must accept them.

`rdf-canonize` happens to make them the same through conversion to JSON-native values, see https://github.com/digitalbazaar/rdf-canonize/issues/10.

**Comment by VladimirAlexiev** [comment]
>  it's not possible to make unit tests for all the cases. 

It is certainly possible to compare values in a more flexible way
